// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protos/databus-serv.proto

package links_shortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OriginalURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//!< Keeps a value1.
	Body string `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *OriginalURL) Reset() {
	*x = OriginalURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_databus_serv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OriginalURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalURL) ProtoMessage() {}

func (x *OriginalURL) ProtoReflect() protoreflect.Message {
	mi := &file_protos_databus_serv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalURL.ProtoReflect.Descriptor instead.
func (*OriginalURL) Descriptor() ([]byte, []int) {
	return file_protos_databus_serv_proto_rawDescGZIP(), []int{0}
}

func (x *OriginalURL) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NewURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *NewURL) Reset() {
	*x = NewURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_databus_serv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewURL) ProtoMessage() {}

func (x *NewURL) ProtoReflect() protoreflect.Message {
	mi := &file_protos_databus_serv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewURL.ProtoReflect.Descriptor instead.
func (*NewURL) Descriptor() ([]byte, []int) {
	return file_protos_databus_serv_proto_rawDescGZIP(), []int{1}
}

func (x *NewURL) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_protos_databus_serv_proto protoreflect.FileDescriptor

var file_protos_databus_serv_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x75, 0x73,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x21, 0x0a, 0x0b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c,
	0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x42, 0x6f, 0x64, 0x79, 0x22, 0x1c, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x55, 0x52, 0x4c, 0x12, 0x12,
	0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x32, 0x64, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x12, 0x11, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x1a,
	0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x52, 0x4c, 0x12, 0x29, 0x0a,
	0x06, 0x72, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x12, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4e,
	0x65, 0x77, 0x55, 0x52, 0x4c, 0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x76, 0x77, 0x69, 0x6e, 0x64, 0x2f, 0x6c, 0x69,
	0x6e, 0x6b, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x3b, 0x6c, 0x69,
	0x6e, 0x6b, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_databus_serv_proto_rawDescOnce sync.Once
	file_protos_databus_serv_proto_rawDescData = file_protos_databus_serv_proto_rawDesc
)

func file_protos_databus_serv_proto_rawDescGZIP() []byte {
	file_protos_databus_serv_proto_rawDescOnce.Do(func() {
		file_protos_databus_serv_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_databus_serv_proto_rawDescData)
	})
	return file_protos_databus_serv_proto_rawDescData
}

var file_protos_databus_serv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_databus_serv_proto_goTypes = []interface{}{
	(*OriginalURL)(nil), // 0: main.OriginalURL
	(*NewURL)(nil),      // 1: main.NewURL
}
var file_protos_databus_serv_proto_depIdxs = []int32{
	0, // 0: main.DataService.shorten:input_type -> main.OriginalURL
	1, // 1: main.DataService.reveal:input_type -> main.NewURL
	1, // 2: main.DataService.shorten:output_type -> main.NewURL
	0, // 3: main.DataService.reveal:output_type -> main.OriginalURL
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_databus_serv_proto_init() }
func file_protos_databus_serv_proto_init() {
	if File_protos_databus_serv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_databus_serv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OriginalURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_databus_serv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_databus_serv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_databus_serv_proto_goTypes,
		DependencyIndexes: file_protos_databus_serv_proto_depIdxs,
		MessageInfos:      file_protos_databus_serv_proto_msgTypes,
	}.Build()
	File_protos_databus_serv_proto = out.File
	file_protos_databus_serv_proto_rawDesc = nil
	file_protos_databus_serv_proto_goTypes = nil
	file_protos_databus_serv_proto_depIdxs = nil
}
